
package org.utopia.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IserviceImplService", targetNamespace = "http://impl.service.utopia.org/", wsdlLocation = "http://localhost:8888/ns?wsdl")
public class IserviceImplService
    extends Service
{

    private final static URL ISERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.utopia.service.impl.IserviceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.utopia.service.impl.IserviceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/ns?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/ns?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ISERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public IserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IserviceImplService() {
        super(ISERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.service.utopia.org/", "IserviceImplService"));
    }

    /**
     * 
     * @return
     *     returns Iservice
     */
    @WebEndpoint(name = "IserviceImplPort")
    public Iservice getIserviceImplPort() {
        return super.getPort(new QName("http://impl.service.utopia.org/", "IserviceImplPort"), Iservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Iservice
     */
    @WebEndpoint(name = "IserviceImplPort")
    public Iservice getIserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.utopia.org/", "IserviceImplPort"), Iservice.class, features);
    }

}
