
package org.utopia.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.utopia.service.ObjectFactory;
import org.utopia.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Iservice", targetNamespace = "http://service.utopia.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Iservice {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.AddResponse")
    public String add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHelloResult", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.utopia.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryUserInfo", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.QueryUserInfo")
    @ResponseWrapper(localName = "queryUserInfoResponse", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.QueryUserInfoResponse")
    public User queryUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.utopia.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryUserList", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.QueryUserList")
    @ResponseWrapper(localName = "queryUserListResponse", targetNamespace = "http://service.utopia.org/", className = "org.utopia.service.QueryUserListResponse")
    public List<User> queryUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
